### PR TITLE
Refactor to a more fluent style

### PR DESCRIPTION
**Pull request by prosac**
Hi @kepet19,

I stumbled upon you project because I started using sway and wanted something like my friend @oem wrote about in a medium article some time ago (https://medium.com/njiuko/using-fzf-instead-of-dmenu-2780d184753f). Suddenly I found myself refactoring it a bit just for the fun of learning a bit of rust. My refactoring is from a very opinionated and rubyish perspective. I love fluent series of transformations without intermediate variables, so I gave it a try to see if such a style is possible in rust.

Let me know what you think!

Cheers from my summer vacations!

Joe/prosac

### CODE REVIEW

**Comment by kkmp-dk** [comment]
Hey, I like your changes!  
I also myself just started out writing rust. 
Then I first made it, I just finished it up and put it on Github. I was planning on refactoring, I like your style! 
I have most of my experience from java!, and I too also don't like many intermediate variables. 
Have you seen the rust programming book?
https://doc.rust-lang.org/stable/book/

**Comment by prosac** [comment]
Cool!

Glad you like it :-)

Yes, I know the book and have it on my reader to read it during my vacation. I am some 30% through I think.

I have another refactoring idea, but I did not manage to get it working:

I would like the `item` comming out of the skim thing to be a struct that knows its identifier, its display string etc. so that

```rust
    let command = item.get(0).unwrap().output();
    let mut command = command.split(" ");

    if command.next().unwrap().contains("Window:") {
        let command = format!("[title=\"{}\"] focus", command.next().unwrap());
        ipc.run_command(&command).unwrap();
    } else {
        let command = format!("exec {}", command.next().unwrap());
        ipc.run_command(&command).unwrap();
    }
```

could be just

```
ipc.run_command(&item.ipc_command).unwrap();
```

The structs then would look something like

```
struct RunningProgram {
    identifier: String
}

struct LaunchableProgram {
    identifier: String
}

impl RunningProgram {
    fn display_string(&self) {
        format!("Window: {}", &self.identifier)
    }

    fn ipc_command(&self) {
        format!("[title=\"{}\"] focus", &self.identifier)
    }
}

impl LaunchableProgram {
    fn display_string(&self) {
        format!("Launch: {}", &self.identifier)
    }

    fn ipc_command(&self) {
        format!("exec {}", &self.identifier)
    }
}
```

**Comment by kkmp-dk** [comment]
I like your idea! 
Do you have the book on a e-reader? 
I first also thought of that, did not implement it. I first just wanted something that did work. 
I find something in skim reader, but right now I am busy studying and working.
https://docs.rs/skim/0.8.2/skim/trait.SkimItem.html

**Comment by kkmp-dk** [comment]
I did change the implementation now, so you can match it like a enum :)

**Comment by prosac** [comment]
i went into full vacation mode after my last post ;-). now i am back at work (for some time already). i am checking out your updated now!

**Comment by kkmp-dk** [comment]
nice, I know the feeling :+1:

**Pull request merged**
